### PR TITLE
Require fully qualified global functions.

### PR DESCRIPTION
**Pull request by kimpepper**
See https://www.deviaene.eu/articles/2023/why-prefix-php-functions-calls-with-backslash/

### CODE REVIEW

**Review by acbramley — APPROVED** [review]

**Comment by dpi** [comment]
I'd say its at odd with public drupal coding standards.

Personally, I dont mind prepending backslash on builtins.

Can we adapt one of the existing test cases?

**Comment by dpi** [comment]
Also document it + rationale in README.

**Comment by dpi** [comment]
Should we mention how to configure phpstorm?

This could be added to the readme.

**Review by dpi — CHANGES_REQUESTED** [review]
tests: adapt from existing

document it + rationale in README.

**Comment by dpi** [comment]
Fixes #80

**Pull request merged**
